In [1]:
#import requests in order to access API and Pandas in order to manipulate dataframe
import requests
import pandas as pd

In [2]:
#get API key from Yelp Business API (https://www.yelp.com/developers/documentation/v3/business_search)
API_KEY = #"ENTER API KEY HERE"
url = "https://api.yelp.com/v3/businesses/search"

In [3]:
#Set default terms - for pizza "NY Style Pizza", for bagel shops "NY Style Bagels", for delis "NY Style delis", for street food 
#stands "street vendors", default location in this case is New York City NY, sort by rating, and set limit to 50 
#for first fifty, set offset to 0, for second fifty set offset to 50
DEFAULT_TERM = "street vendors"
DEFAULT_LOCATION = "New York City NY"
SORT = "rating"
LIMIT = "50"
OFFSET = "0"

In [4]:
#Set headers for API 
headers = {'Authorization': 'Bearer {}'.format(API_KEY)}

In [5]:
#Set parameters for API pull 
url_params = {
'term': DEFAULT_TERM, 
'location': DEFAULT_LOCATION, 
'sort_by': SORT,
'limit':LIMIT,
'offset':OFFSET
}

In [6]:
#Pull API with parameters
response = requests.request('GET', url, headers=headers, params=url_params)

In [7]:
#Pull information needed into different lines for the data table 
#Because not every restaurant has a cost, use a try except for the key error to put in "No data found" in order to be able to 
#run the code. 
name = []
rating = []
reviews = []
address = []
zip_code = []
cost = []
url = []
lat = []
lng = []
for business in response.json()["businesses"]:
        name.append(business["name"])
        rating.append(business["rating"])
        reviews.append(business["review_count"])
        address.append(business["location"]["display_address"][0])
        try:
            cost.append(business["price"])
        except:
            cost.append("No data found")
        zip_code.append(business["location"]["zip_code"])
        url.append(business["url"])
        lat.append(business["coordinates"]["latitude"])
        lng.append(business["coordinates"]["longitude"])

In [8]:
#set a table with the information pulled 
data = {"Name":name,"Rating":rating,"Review Count":reviews,"Price":cost,"Street Address":address,"Zip Code":zip_code,"Latitude":lat,"Longitude":lng,"Url":url}

In [9]:
#set data as a pandas dataframe 
df = pd.DataFrame(data)

In [10]:
#save information to CSV in order to continue to manipulate 
df.to_csv("../csv_repository/Yelp_API_Pull/Top_0-50_NYCstreetvendors.csv")

In [11]:
#pull in all dataframes 
df1 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_0-50_NYStyle_Pizza.csv")
df2 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_50-100_NYStyle_pizza.csv")
df3 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_0-50_NYStyle_deli.csv")
df4 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_50-100_NYStyle_deli.csv")
df5 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_0-50_NYStyle_bagels.csv")
df6 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_50-100_NYStyle_bagels.csv")
df7 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_0-50_NYCstreetvendors.csv")
df8 = pd.read_csv("../csv_repository/Yelp_API_Pull/Top_50-100_NYCstreetvendors.csv")

In [12]:
#create top 100 lists by concatenating 
pizza = pd.concat([df1, df2])
deli = pd.concat([df3, df4])
bagel = pd.concat([df5, df6])
streetfood = pd.concat([df7, df8])

In [13]:
#drop the index column in all dataframes 
pizza = pizza.drop(columns=["Unnamed: 0"])
bagel = bagel.drop(columns = ["Unnamed: 0"])
deli = deli.drop(columns = ["Unnamed: 0"])
streetfood = streetfood.drop(columns = ["Unnamed: 0"])

In [14]:
#Add a category column later for manipulation in JS
pizza["Category"] = "Pizza"
bagel["Category"] = "Bagel"
deli["Category"] = "Deli"
streetfood["Category"] = "Street Food"

In [15]:
#save as top 100 lists of each category
pizza.to_csv("../csv_repository/Top_100_Each_Category/Top_100_NYStyle_Pizza.csv")
bagel.to_csv("../csv_repository/Top_100_Each_Category/Top_100_NYStyle_Bagel.csv")
deli.to_csv("../csv_repository/Top_100_Each_Category/Top_100_NYStyle_Deli.csv")
streetfood.to_csv("../csv_repository/Top_100_Each_Category/Top_100_NY_streetvendors.csv")

In [16]:
#Check dataframes to confirm data saved to csvs
pizza.head()

,Name,Rating,Review Count,Price,Street Address,Zip Code,Latitude,Longitude,Url,Category
0,Scott's Pizza Tours,5.0,314,$$,"New York, NY 10001",10001,40.750244,-73.997025,https://www.yelp.com/biz/scotts-pizza-tours-ne...,Pizza
1,L'industrie Pizzeria,4.5,532,$,254 S 2nd St,11211,40.711620,-73.957830,https://www.yelp.com/biz/l-industrie-pizzeria-...,Pizza
2,B Side Pizza & Wine Bar,4.5,1140,$$,370 W 51st St,10019,40.763940,-73.988340,https://www.yelp.com/biz/b-side-pizza-and-wine...,Pizza
3,Song E Napule,4.5,483,$$,146 W Houston St,10012,40.728130,-74.001880,https://www.yelp.com/biz/song-e-napule-new-yor...,Pizza
4,Sottocasa Pizzeria - Harlem,4.5,265,$$,227 Lenox Ave,10027,40.805587,-73.947547,https://www.yelp.com/biz/sottocasa-pizzeria-ha...,Pizza

In [17]:
bagel.head()

,Name,Rating,Review Count,Price,Street Address,Zip Code,Latitude,Longitude,Url,Category
0,Best Bagel & Coffee,4.5,3325,$,225 W 35th St,10001,40.752268,-73.991086,https://www.yelp.com/biz/best-bagel-and-coffee...,Bagel
1,Liberty Bagels Midtown,4.5,525,$,260 W 35th St,10001,40.752550,-73.992490,https://www.yelp.com/biz/liberty-bagels-midtow...,Bagel
2,Russ & Daughters,4.5,2237,$$,179 E Houston St,10002,40.722589,-73.988283,https://www.yelp.com/biz/russ-and-daughters-ne...,Bagel
3,Mixtape Bushwick,4.5,78,$,1533 Myrtle Ave,11237,40.699494,-73.914020,https://www.yelp.com/biz/mixtape-bushwick-broo...,Bagel
4,Absolute Bagels,4.5,1411,$,2788 Broadway,10025,40.802510,-73.967450,https://www.yelp.com/biz/absolute-bagels-new-y...,Bagel

In [18]:
deli.head()

,Name,Rating,Review Count,Price,Street Address,Zip Code,Latitude,Longitude,Url,Category
0,Sunny and Annie's,4.5,488,$,94 Ave B,10003,40.724653,-73.981702,https://www.yelp.com/biz/sunny-and-annies-new-...,Deli
1,Lioni Italian Heroes,4.5,373,$$,7803 15th Ave,11228,40.615720,-74.004820,https://www.yelp.com/biz/lioni-italian-heroes-...,Deli
2,David's Brisket House and Deli,4.5,447,$$,533 Nostrand Ave,11216,40.679434,-73.949515,https://www.yelp.com/biz/davids-brisket-house-...,Deli
3,Katz's Delicatessen,4.0,12382,$$,205 E Houston St,10002,40.722237,-73.987526,https://www.yelp.com/biz/katzs-delicatessen-ne...,Deli
4,TK's Deli,5.0,22,$,954 Broadway,11206,40.696700,-73.935010,https://www.yelp.com/biz/tks-deli-brooklyn?adj...,Deli

In [19]:
streetfood.head()

,Name,Rating,Review Count,Price,Street Address,Zip Code,Latitude,Longitude,Url,Category
0,Royal Grill Halal Food,5.0,357,$,44TH St And 6th Ave,10018.0,40.756140,-73.983160,https://www.yelp.com/biz/royal-grill-halal-foo...,Street Food
1,Tony Dragon's Grille,4.5,221,$,62nd St and Madison Ave,10065.0,40.765470,-73.970040,https://www.yelp.com/biz/tony-dragons-grille-n...,Street Food
2,Xinjiang BBQ Cart,4.5,329,$,41ST Ave,11355.0,40.758665,-73.829384,https://www.yelp.com/biz/xinjiang-bbq-cart-flu...,Street Food
3,Williamsburg Smorgasburg - Saturday,4.5,1121,$$,90 Kent Ave,11211.0,40.721021,-73.962177,https://www.yelp.com/biz/williamsburg-smorgasb...,Street Food
4,The Halal Guys,4.0,9501,$,W 53rd St,10019.0,40.764770,-73.986140,https://www.yelp.com/biz/the-halal-guys-new-yo...,Street Food